server:
  port: 8090

spring:
  application:
    name: wxpay-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/payment?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    # username: root
    # password: li123456
    url: ENC(fmE80m0JpebZ2yTR+CudyaoV3Ovxnc4ZxTose7aQx0TiJQLzqZwNm4oCAPlBUxABZEIjAe2GS/eAkpURokObyPTUIOc0LNIGGYk8u+D18I0JF6UIkb4OgAAVrvHpps2dthRyvmHrOuX2xnXy17XOYFqWUITpIhFu)
    username: ENC(N/VV+NdIqk47bcWWNHteGqFAa2dkx1gu)
    password: ENC(Raat1e9S3teQBck4MGZHbtY5ZaE7EDzEmzaioLFtoiQ=)
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8088
  redis:
    host: localhost
    # password: li123456
    password: ENC(Raat1e9S3teQBck4MGZHbtY5ZaE7EDzEmzaioLFtoiQ=)
    port: 6379

mybatis-plus:
  configuration:
    # sql日志记录
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    top.rectorlee.mapper: debug

jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWithMD5AndDES
    # 加密密钥
    password: Lee
    property:
      # 前缀
      prefix: "ENC("
      # 后缀
      suffix: ")"
