server:
  port: 8090

spring:
  application:
    name: wxpay-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: li123456
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8088
  redis:
    host: localhost
    password: li123456
    port: 6379

mybatis-plus:
  configuration:
    # sql日志记录
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    top.rectorlee.mapper: debug
